{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "b4d0f88d",
   "metadata": {},
   "source": [
    "# Assignment_6"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "35011967",
   "metadata": {},
   "source": [
    "#### Q1. Describe three applications for exception processing."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "ebd7c099",
   "metadata": {},
   "source": [
    "Exception processing is a crucial aspect of handling errors and exceptional situations in programming. Here are three applications for exception processing:\n",
    "\n",
    "1. Error Handling: Exceptions are commonly used to handle errors that may occur during program execution. For example, if a file cannot be opened, an exception can be raised to handle the error gracefully, allowing the program to respond appropriately rather than crashing or producing incorrect results.\n",
    "\n",
    "2. Input Validation: Exceptions can be used to validate user input and handle invalid or unexpected values. For instance, if a user enters an invalid data format in a form, an exception can be raised to prompt the user to correct the input.\n",
    "\n",
    "3. Resource Management: Exceptions play a role in managing system resources effectively. They allow for proper cleanup and deallocation of resources like files, database connections, or network sockets in case of exceptions. By catching exceptions and releasing resources, you can ensure that your program maintains proper resource utilization and doesn't leave any dangling resources."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "9b0de2d7",
   "metadata": {},
   "source": [
    "#### Q2. What happens if you don&#39;t do something extra to treat an exception?"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "5ad2dff9",
   "metadata": {},
   "source": [
    "If an exception is not treated or handled in some way, it will result in an unhandled exception error, which typically causes the program to terminate abruptly. The error message traceback will be displayed, showing the location and nature of the unhandled exception. Without exception handling, the program's execution will stop, and any remaining code will not be executed."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "6392e070",
   "metadata": {},
   "source": [
    "#### Q3. What are your options for recovering from an exception in your script?"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "fc19696b",
   "metadata": {},
   "source": [
    "1. Catch and Handle: You can use try-except blocks to catch specific exceptions and handle them gracefully. Inside the except block, you can provide code to address the exception, such as displaying an error message, logging the error, or taking alternative actions to resolve the issue and continue the program's execution.\n",
    "\n",
    "2. Retry Mechanism: In some cases, you may want to retry the operation that caused the exception. By placing the code inside a loop, you can attempt the operation again until it succeeds or a maximum number of retries is reached.\n",
    "\n",
    "3. Graceful Exit: If the exception is severe or cannot be recovered from, you can terminate the script gracefully by catching the exception, performing any necessary cleanup, and then exiting the script using the sys.exit() function."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "12855118",
   "metadata": {},
   "source": [
    "#### Q4. Describe two methods for triggering exceptions in your script."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "c0ba1f63",
   "metadata": {},
   "source": [
    "There are several methods for triggering exceptions in a script:\n",
    "\n",
    "1. Raise Statement: You can use the raise statement to explicitly raise an exception at a specific point in your code. By providing an exception type or creating a custom exception, you can trigger an exception with a specific message or context.\n",
    "\n",
    "2. Built-in Exceptions: Python provides built-in exceptions that can be triggered in different scenarios. For example, you can cause a ZeroDivisionError by attempting to divide a number by zero or raise a ValueError by passing an invalid argument to a function."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "65ea2062",
   "metadata": {},
   "source": [
    "#### Q5. Identify two methods for specifying actions to be executed at termination time, regardless of whether or not an exception exists."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "5351c968",
   "metadata": {},
   "source": [
    "1. Finally Block: In Python, you can use a finally block in conjunction with a try-except block. The code within the finally block is executed regardless of whether an exception occurred or not. It is commonly used to release resources, close files, or perform cleanup operations that need to be executed regardless of exceptions.\n",
    "\n",
    "2. Context Managers: Context managers, implemented using the with statement, allow you to define setup and teardown actions for resources. By implementing the **_ _enter_ _** and **_ _exit_ _** methods in a class, you can specify actions to be executed when entering and exiting a context. The **_ _exit_ _** method is always called, even if an exception occurs within the context, making it suitable for cleanup operations."
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.8"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
